
package com.cabanaban.desklo.ui.desktop;

import com.cabanaban.desklo.ui.CloseTicketViewModelObserver;
import com.cabanaban.desklo.viewmodel.CloseTicketViewModel;
import com.cabanaban.desklo.Services;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.HashMap;


public class CloseTicketDialogUI extends javax.swing.JDialog implements CloseTicketViewModelObserver {
    
    private String ticketID;
    private Services services;
    
    /** Creates new form CloseTicketDialogUI */
    public CloseTicketDialogUI(java.awt.Frame parent, boolean modal, Services services) {
        super(parent, modal);
        initComponents();
        this.services = services;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        durationLabel = new javax.swing.JLabel();
        durationTextField = new javax.swing.JFormattedTextField();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        durationLabel.setText("durationLabel");

        durationTextField.setText("durationTextField");

        buttonOk.setText("buttonOk");

        buttonCancel.setText("buttonCancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(durationLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCancel))
                    .addComponent(durationTextField))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationLabel)
                    .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void update(CloseTicketViewModel closeTicketViewModel) {
        setTitle(closeTicketViewModel.title);
        ticketID = closeTicketViewModel.ticketID;
        durationLabel.setText(closeTicketViewModel.durationLabel);
        durationTextField.setText(closeTicketViewModel.durationValue);
        buttonOk.setText(closeTicketViewModel.okLabel);
        buttonCancel.setText(closeTicketViewModel.cancelLabel);
        if (buttonOk.getActionListeners().length == 0) {
            buttonOk.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    HashMap<String,String> request = new HashMap<String,String>();
                    request.put("ticketID", ticketID);
                    services.getDispatcher().dispatch(closeTicketViewModel.okAction, request);
                }
            });
            
            buttonCancel.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    HashMap<String,String> request = new HashMap<String,String>();
                    request.put("ticketID", ticketID);
                    services.getDispatcher().dispatch(closeTicketViewModel.cancelAction, request);
                }
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JFormattedTextField durationTextField;
    // End of variables declaration//GEN-END:variables

}
