/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cabanaban.desklo.ui.desktop;

import com.cabanaban.desklo.viewmodel.TicketListViewModel;
import com.cabanaban.desklo.viewmodel.TicketListItemViewModel;
import com.cabanaban.desklo.Services;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BoxLayout;


/**
 *
 * @author henrique
 */
public class TicketListUI extends javax.swing.JInternalFrame {

    private final Services services;

    /**
     * Creates new form TicketListUI
     *
     * @param services
     */
    public TicketListUI(Services services) {
        this.services = services;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        affectedUserLabel = new javax.swing.JLabel();
        supporterLabel = new javax.swing.JLabel();
        elapsedTimeLabel = new javax.swing.JLabel();
        problemLabel = new javax.swing.JLabel();
        actionLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollViewPort = new javax.swing.JPanel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(998, 600));

        affectedUserLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        affectedUserLabel.setText("affectedUserLabel");

        supporterLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        supporterLabel.setText("supporterLabel");

        elapsedTimeLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        elapsedTimeLabel.setText("elapsedTimeLabel");
        elapsedTimeLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        elapsedTimeLabel.setName(""); // NOI18N

        problemLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        problemLabel.setText("problemLabel");

        actionLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        actionLabel.setText("actionLabel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(affectedUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supporterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elapsedTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(problemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(actionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(affectedUserLabel)
                            .addComponent(supporterLabel)
                            .addComponent(problemLabel)
                            .addComponent(actionLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(elapsedTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout scrollViewPortLayout = new javax.swing.GroupLayout(scrollViewPort);
        scrollViewPort.setLayout(scrollViewPortLayout);
        scrollViewPortLayout.setHorizontalGroup(
            scrollViewPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
        );
        scrollViewPortLayout.setVerticalGroup(
            scrollViewPortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(scrollViewPort);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JLabel affectedUserLabel;
    private javax.swing.JLabel elapsedTimeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel problemLabel;
    private javax.swing.JPanel scrollViewPort;
    private javax.swing.JLabel supporterLabel;
    // End of variables declaration//GEN-END:variables

    public void refreshData(TicketListViewModel ticketListViewModel) {
        actionLabel.setText(ticketListViewModel.actionHeaderLabel);
        affectedUserLabel.setText(ticketListViewModel.affectUserHeaderLabel);
        elapsedTimeLabel.setText(ticketListViewModel.elapsedTimeHeaderLabel);
        problemLabel.setText(ticketListViewModel.problemHeaderLabel);
        supporterLabel.setText(ticketListViewModel.supporterHeaderLabel);
        setTitle(ticketListViewModel.title);
        refreshItems(ticketListViewModel.ticketListItemsViewModel);
    }

    private void refreshItems(List<TicketListItemViewModel> ticketListItemsViewModel) {
        scrollViewPort.removeAll();
        scrollViewPort.setLayout(new BoxLayout(scrollViewPort, BoxLayout.Y_AXIS));
        for (TicketListItemViewModel ticketListItemViewModel : ticketListItemsViewModel) {
            TicketManagerUIComponent ticketManagerUIComponent = new TicketManagerUIComponent(services);
            ticketManagerUIComponent.refreshData(ticketListItemViewModel);
            ticketManagerUIComponent.setMaximumSize(new Dimension(1230, 120));
            scrollViewPort.add(ticketManagerUIComponent);            
        }

    }

}
