package com.cabanaban.desklo.controller;

public enum Action {

    NOP, SHOW_MAIN, SHOW_OWN_TICKETS, SHOW_OPEN_TICKET, SHOW_MANAGE_TICKETS,
    SHOW_MANAGE_USERS, SHOW_TICKET_DASHBOARD, SHOW_SELECT_USER, SHOW_MANAGE_TICKET,
    SHOW_ATTEND_TICKET, SHOW_TRANSFER_TICKET, SHOW_CLOSE_TICKET, CLOSE_TICKET, CANCEL_CLOSE_TICKET;

}
