package com.cabanaban.desklo.controller;

public enum Action {
    NOP, SHOW_MAIN, SHOW_MANAGE_TICKETS,
    SHOW_MANAGE_USERS,
    SHOW_CLOSE_TICKET, CLOSE_TICKET, CANCEL_CLOSE_TICKET,
    SHOW_OPEN_TICKET, CANCEL_OPEN_TICKET, OPEN_TICKET,
    CANCEL_MY_TICKETS, SHOW_MY_TICKETS,
    SHOW_SELECT_USER, CANCEL_SELECT_USER, SELECT_USER,
    SHOW_TICKET_DASHBOARD, CANCEL_TICKET_DASHBOARD,
    SHOW_ATTEND_TICKET, CANCEL_ATTEND_TICKET, ATTEND_TICKET,
    SHOW_TRANSFER_TICKET, CANCEL_TRANSFER_TICKET, TRANSFER_TICKET,
    SHOW_EDIT_USER, CANCEL_EDIT_USER, EDIT_USER,
    SHOW_NEW_USER, CANCEL_NEW_USER, NEW_USER;
}
