

package com.cabanaban.desklo.presentation.ui.desktop;

import com.cabanaban.desklo.Services;
import com.cabanaban.desklo.presentation.viewmodel.AttendTicketViewModel;

import java.awt.FlowLayout;

public class AttendTicketDialogUI extends javax.swing.JDialog {
    
    private Services services;
    private AttendTicketFormUI attendTicketForm; 
    
    /** Creates new form AttendTicketDialogUI */
    public AttendTicketDialogUI(java.awt.Frame parent, boolean modal, Services services) {
        super(parent, modal);
        this.services = services;
        this.attendTicketForm = new AttendTicketFormUI(services);
        initComponents();
        initForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initForm() {
        FlowLayout layot = new FlowLayout();
        getContentPane().setLayout(layot);
        getContentPane().add(attendTicketForm);
        setSize(400, 200);
    }

    public void update(AttendTicketViewModel attendTicketViewModel) {
        setTitle(attendTicketViewModel.title);
        attendTicketForm.update(attendTicketViewModel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
